#!/bin/bash
rm -vrf `find .. -depth -type f -or -type d | grep -vE '\.\.\/([mM]ockup|plan|profiling|src|debugging\.PNG|dokumentace\.pdf|screenshot\.PNG|skutecnost\.txt|hodnoceni\.txt|odevzdani\.txt|README\.md|\.git(|\/*)|\.editorconfig|LICENSE)'`
rm -vrf `find ../plan -depth -type f -or -type d | grep -vE "^\.\.\/plan$" | grep -vE '^\.\.\/plan\/xpastu04_xcaras00_xsenic00_xtomas34\.txt'`
rm -vrf `find ../profiling -depth -type f -or -type d | grep -vE "^\.\.\/profiling" | grep -vE '^\.\.\/profiling\/(report\.pdf|stdin[1-3]\.txt)'`
rm -vrf `find ../src -depth -type f -or -type d | grep -vE "^\.\.\/src$" | grep -vE '^\.\.\/src\/(Tests\/*|Profiling\/*|ivs_project2\/*|xpastu04_xcaras00_xsenic00_xtomas34\/*|Doxyfile*|MakefileLin|MakefileWin|clean\.bat|help\.bat|icon.ico|pack\.bat|ignore\.txt|dataIn\.txt|del)'`
rm -vrf `find ../../doc -depth -type f -or -type d | grep -vE "^\.\.\/\.\.\/doc$" | grep -vE '^\.\.\/\.\.\/doc\/(html\/*)'`
rm -vrf `find ../../install -depth -type f -or -type d | grep -vE "^\.\.\/\.\.\/install$" | grep -vE '^\.\.\/\.\.\/install\/(xpastu04_xcaras00_xsenic00_xtomas34.msi|setup.exe)'`
